### Basics of numpy array 

In [1]:
import numpy as np

#### Generate random array of 5 elements

In [5]:
x = np.random.randint(10, size=5)
print(x)

[2 1 6 6 5]


#### Access single element of array at any position

In [6]:
x[2]

6

#### Access Last element of array

In [7]:
x[-1]

5

#### Generate multi dimensional array

In [11]:
y = np.arange(1,11).reshape(5,2)
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### Access elements from multi-dimensional array

In [12]:
y[0,0]

1

In [13]:
y[-1,-1]

10

#### values can also be modified using index

In [15]:
y[0,0] = 0
print(y)

[[ 0  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Here is one thing to note, unlike python, numpy can modify values but if you are trying to insert floating point values in integer array,<br> then it will simply truncate value & integer value will be stored in array

In [17]:
y[0,0] = 1.5
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### Generate 1d array of integer values from 1 to 10

In [22]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


#### Slicing an Array

Syntax : <br>arr[start:stop:step]

In [24]:
arr[0:5:2]

array([1, 3, 5])

In [26]:
arr[0:3]

array([1, 2, 3])

In [28]:
arr[3:7]

array([4, 5, 6, 7])

In [29]:
arr[:2]

array([1, 2])

In [31]:
arr[::2]                         # every element of array with step 2

array([1, 3, 5, 7, 9])

In [32]:
arr[1::2]                       # every other element starting from index 1 

array([ 2,  4,  6,  8, 10])

In [34]:
arr[::-1]                       # Reverse arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [39]:
arr[5::-1]                      # starting from 5 th index reverse all elements

array([6, 5, 4, 3, 2, 1])

In [41]:
arr[5::-2]                     # starting from 5th index reverse all elements by step 2

array([6, 4, 2])

#### Multi-dimensional sub-array

#### create multi-dimensional array

In [2]:
arr1 = np.arange(1,13).reshape(4,3)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Access 3 rows & 2 cols from above multi-dimensional array

In [5]:
arr1[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

#### reverse array

In [6]:
arr1[::-1]

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

#### reverse rows & cols 

In [10]:
arr1[::-1,::-1]

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

#### Access 1st col of array

In [12]:
arr1[:,0]

array([ 1,  4,  7, 10])

#### Access 1st row of array

In [13]:
arr1[0,:]

array([1, 2, 3])

#### Create an array with np.array

In [21]:
x = np.array([[1,2,3],[2,3,4],[0,9,8]])
print(x)

[[1 2 3]
 [2 3 4]
 [0 9 8]]


In [22]:
x.reshape(1,9)

array([[1, 2, 3, 2, 3, 4, 0, 9, 8]])

#### Concatenation of array

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([a,b])
print(c)

[1 2 3 4 5 6]


You can concatenate more than 2 array at a time in same way.<br>
You can concatenate multi-dimensional array as well

In [26]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(2,8).reshape(2,3)
z = np.concatenate([x,y])
print(z)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]


#### For working with array of different dimensions, use vstack or hstack

In [31]:
x = np.array([1,2,3])
y = np.arange(1,7).reshape(2,3)
#print(x,y)
z = np.vstack([x,y])
print(z)

[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [32]:
x = np.array([1,2,3])
y = np.arange(1,7).reshape(2,3)
#print(x,y)
z = np.vstack([y,x])
print(z)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


#### Splitting of array

In [46]:
x = [1,2,3,4,5,6,7,8]
x1,x2,x3 = np.split(x,[2,3])
print(x1,x2,x3)

[1 2] [3] [4 5 6 7 8]


In [49]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
